/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsPreWritingRouteImport } from './routes/programs.pre-writing'
import { Route as ProgramsPhonicsRouteImport } from './routes/programs.phonics'
import { Route as ProgramsKindergartenTuitionRouteImport } from './routes/programs.kindergarten-tuition'
import { Route as ProgramsHandwritingRouteImport } from './routes/programs.handwriting'
import { Route as ProgramsDrawingRouteImport } from './routes/programs.drawing'
import { Route as ProgramsChessRouteImport } from './routes/programs.chess'
import { Route as ProgramsAiRoboticsRouteImport } from './routes/programs.ai-robotics'
import { Route as ProgramsAbacusRouteImport } from './routes/programs.abacus'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsPreWritingRoute = ProgramsPreWritingRouteImport.update({
  id: '/pre-writing',
  path: '/pre-writing',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsPhonicsRoute = ProgramsPhonicsRouteImport.update({
  id: '/phonics',
  path: '/phonics',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsKindergartenTuitionRoute =
  ProgramsKindergartenTuitionRouteImport.update({
    id: '/kindergarten-tuition',
    path: '/kindergarten-tuition',
    getParentRoute: () => ProgramsRoute,
  } as any)
const ProgramsHandwritingRoute = ProgramsHandwritingRouteImport.update({
  id: '/handwriting',
  path: '/handwriting',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsDrawingRoute = ProgramsDrawingRouteImport.update({
  id: '/drawing',
  path: '/drawing',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsChessRoute = ProgramsChessRouteImport.update({
  id: '/chess',
  path: '/chess',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsAiRoboticsRoute = ProgramsAiRoboticsRouteImport.update({
  id: '/ai-robotics',
  path: '/ai-robotics',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsAbacusRoute = ProgramsAbacusRouteImport.update({
  id: '/abacus',
  path: '/abacus',
  getParentRoute: () => ProgramsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/programs/abacus': typeof ProgramsAbacusRoute
  '/programs/ai-robotics': typeof ProgramsAiRoboticsRoute
  '/programs/chess': typeof ProgramsChessRoute
  '/programs/drawing': typeof ProgramsDrawingRoute
  '/programs/handwriting': typeof ProgramsHandwritingRoute
  '/programs/kindergarten-tuition': typeof ProgramsKindergartenTuitionRoute
  '/programs/phonics': typeof ProgramsPhonicsRoute
  '/programs/pre-writing': typeof ProgramsPreWritingRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/programs/abacus': typeof ProgramsAbacusRoute
  '/programs/ai-robotics': typeof ProgramsAiRoboticsRoute
  '/programs/chess': typeof ProgramsChessRoute
  '/programs/drawing': typeof ProgramsDrawingRoute
  '/programs/handwriting': typeof ProgramsHandwritingRoute
  '/programs/kindergarten-tuition': typeof ProgramsKindergartenTuitionRoute
  '/programs/phonics': typeof ProgramsPhonicsRoute
  '/programs/pre-writing': typeof ProgramsPreWritingRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/programs/abacus': typeof ProgramsAbacusRoute
  '/programs/ai-robotics': typeof ProgramsAiRoboticsRoute
  '/programs/chess': typeof ProgramsChessRoute
  '/programs/drawing': typeof ProgramsDrawingRoute
  '/programs/handwriting': typeof ProgramsHandwritingRoute
  '/programs/kindergarten-tuition': typeof ProgramsKindergartenTuitionRoute
  '/programs/phonics': typeof ProgramsPhonicsRoute
  '/programs/pre-writing': typeof ProgramsPreWritingRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/programs'
    | '/sitemap.xml'
    | '/programs/abacus'
    | '/programs/ai-robotics'
    | '/programs/chess'
    | '/programs/drawing'
    | '/programs/handwriting'
    | '/programs/kindergarten-tuition'
    | '/programs/phonics'
    | '/programs/pre-writing'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/sitemap.xml'
    | '/programs/abacus'
    | '/programs/ai-robotics'
    | '/programs/chess'
    | '/programs/drawing'
    | '/programs/handwriting'
    | '/programs/kindergarten-tuition'
    | '/programs/phonics'
    | '/programs/pre-writing'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/programs'
    | '/sitemap.xml'
    | '/programs/abacus'
    | '/programs/ai-robotics'
    | '/programs/chess'
    | '/programs/drawing'
    | '/programs/handwriting'
    | '/programs/kindergarten-tuition'
    | '/programs/phonics'
    | '/programs/pre-writing'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/pre-writing': {
      id: '/programs/pre-writing'
      path: '/pre-writing'
      fullPath: '/programs/pre-writing'
      preLoaderRoute: typeof ProgramsPreWritingRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/phonics': {
      id: '/programs/phonics'
      path: '/phonics'
      fullPath: '/programs/phonics'
      preLoaderRoute: typeof ProgramsPhonicsRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/kindergarten-tuition': {
      id: '/programs/kindergarten-tuition'
      path: '/kindergarten-tuition'
      fullPath: '/programs/kindergarten-tuition'
      preLoaderRoute: typeof ProgramsKindergartenTuitionRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/handwriting': {
      id: '/programs/handwriting'
      path: '/handwriting'
      fullPath: '/programs/handwriting'
      preLoaderRoute: typeof ProgramsHandwritingRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/drawing': {
      id: '/programs/drawing'
      path: '/drawing'
      fullPath: '/programs/drawing'
      preLoaderRoute: typeof ProgramsDrawingRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/chess': {
      id: '/programs/chess'
      path: '/chess'
      fullPath: '/programs/chess'
      preLoaderRoute: typeof ProgramsChessRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/ai-robotics': {
      id: '/programs/ai-robotics'
      path: '/ai-robotics'
      fullPath: '/programs/ai-robotics'
      preLoaderRoute: typeof ProgramsAiRoboticsRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/abacus': {
      id: '/programs/abacus'
      path: '/abacus'
      fullPath: '/programs/abacus'
      preLoaderRoute: typeof ProgramsAbacusRouteImport
      parentRoute: typeof ProgramsRoute
    }
  }
}

interface ProgramsRouteChildren {
  ProgramsAbacusRoute: typeof ProgramsAbacusRoute
  ProgramsAiRoboticsRoute: typeof ProgramsAiRoboticsRoute
  ProgramsChessRoute: typeof ProgramsChessRoute
  ProgramsDrawingRoute: typeof ProgramsDrawingRoute
  ProgramsHandwritingRoute: typeof ProgramsHandwritingRoute
  ProgramsKindergartenTuitionRoute: typeof ProgramsKindergartenTuitionRoute
  ProgramsPhonicsRoute: typeof ProgramsPhonicsRoute
  ProgramsPreWritingRoute: typeof ProgramsPreWritingRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsAbacusRoute: ProgramsAbacusRoute,
  ProgramsAiRoboticsRoute: ProgramsAiRoboticsRoute,
  ProgramsChessRoute: ProgramsChessRoute,
  ProgramsDrawingRoute: ProgramsDrawingRoute,
  ProgramsHandwritingRoute: ProgramsHandwritingRoute,
  ProgramsKindergartenTuitionRoute: ProgramsKindergartenTuitionRoute,
  ProgramsPhonicsRoute: ProgramsPhonicsRoute,
  ProgramsPreWritingRoute: ProgramsPreWritingRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
